apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.motdepasse }}
  DATABASE_URL: postgres://livredor:{{ .Values.motdepasse }}@{{ .Release.Name }}-db:5432/livredor
